In [1]:
import numpy as np

In [60]:
matrix1 = [[5, 1, 6], [7, 3, 6], [9, 0, 4]]
matrix2 = [[6, 3, 7], [4, 1, 7], [9, 5, 3]]
matrix3 = [[5, 3, 7], [8, 4, 3], [7, 4, 7]]
matrix1 = np.matrix(matrix1)
matrix2 = np.matrix(matrix2)
matrix3 = np.matrix(matrix3)
print(matrix1)
print(matrix2)

[[5 1 6]
 [7 3 6]
 [9 0 4]]
[[6 3 7]
 [4 1 7]
 [9 5 3]]


In [20]:
matrix_t = matrix1.transpose()
print(matrix_t)

[[5 7 9]
 [1 3 0]
 [6 6 4]]


In [21]:
matrix_double_t = matrix_t.transpose()
print(matrix_double_t == matrix1)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [22]:
matrix_sum = matrix1 + matrix2
sum_t = matrix_sum.transpose()
matrix_sum_t = matrix1.transpose() + matrix2.transpose()
print( sum_t == matrix_sum_t)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [23]:
matrix_proiz = matrix2 * matrix1
proiz_t = matrix_sum.transpose()
matrix_proiz_t = matrix1.transpose() * matrix2.transpose()
print( sum_t == matrix_sum_t)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [24]:
det = np.linalg.det(matrix1)
det_t = np.linalg.det(matrix1.transpose())
print(det)
print(det_t)

-76.0
-76.0


In [25]:
print(matrix1)
print(matrix1 * 5)

[[5 1 6]
 [7 3 6]
 [9 0 4]]
[[25  5 30]
 [35 15 30]
 [45  0 20]]


In [26]:
print(matrix1)
print(matrix1 * 0)

[[5 1 6]
 [7 3 6]
 [9 0 4]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [27]:
s = 5 + 3 + 4
print( matrix1 * s)
print( matrix1 * 5 + matrix1 * 3 + matrix1 * 4)

[[ 60  12  72]
 [ 84  36  72]
 [108   0  48]]
[[ 60  12  72]
 [ 84  36  72]
 [108   0  48]]


In [28]:
p = 5 * 6
print(matrix1 * p)
print(matrix1 * 6 * 5)

[[150  30 180]
 [210  90 180]
 [270   0 120]]
[[150  30 180]
 [210  90 180]
 [270   0 120]]


In [29]:
print((matrix1 + matrix2) * 3)
print(matrix1 * 3 + matrix2 * 3)

[[33 12 39]
 [33 12 39]
 [54 15 21]]
[[33 12 39]
 [33 12 39]
 [54 15 21]]


In [30]:
print(matrix1 + matrix2)
print(matrix2 + matrix1)

[[11  4 13]
 [11  4 13]
 [18  5  7]]
[[11  4 13]
 [11  4 13]
 [18  5  7]]


In [31]:
print(matrix1 + (matrix2 + matrix3))
print((matrix1 + matrix2) + matrix3)

[[16  7 20]
 [19  8 16]
 [25  9 14]]
[[16  7 20]
 [19  8 16]
 [25  9 14]]


In [32]:
print(matrix1 + (-1) * matrix1)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [33]:
print(matrix1 * (matrix2 * matrix3))
print((matrix1 * matrix2) * matrix3)

[[1228  688 1174]
 [1588  892 1534]
 [1351  758 1296]]
[[1228  688 1174]
 [1588  892 1534]
 [1351  758 1296]]


In [34]:
print(matrix1 * (matrix2 + matrix3))
print(matrix1 * matrix2 + matrix1 * matrix3)

[[163  89 140]
 [209 111 188]
 [163  90 166]]
[[163  89 140]
 [209 111 188]
 [163  90 166]]


In [35]:
print(matrix1 * matrix2)
print(matrix2 * matrix1)

[[ 88  46  60]
 [108  54  88]
 [ 90  47  75]]
[[114  15  82]
 [ 90   7  58]
 [107  24  96]]


In [37]:
e = np.matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print(e * matrix1 == matrix1 * e)
print(e * matrix1 == matrix1)
print(e * matrix1)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[5 1 6]
 [7 3 6]
 [9 0 4]]


In [44]:
z = np.matrix([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
print(z * matrix1 == matrix1 * z)
print(z * matrix1 == z)
print(z * matrix1)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [45]:
print(np.linalg.det(matrix1))
print(np.linalg.det(matrix1.transpose()))

-76.0
-76.0


In [46]:
A = np.matrix([[6, 3, 5], [0, 0, 0], [7, 3, 6]])
print(np.linalg.det(A))

0.0


In [61]:
a = [[5, 3, 7], [8, 4, 3], [7, 4, 7]]
a = np.matrix(a)
b = [[5, 3, 7], [7, 4, 7], [8, 4, 3]]
b = np.matrix(b)
print(np.linalg.det(a))
print(np.linalg.det(b))

2.9999999999999996
-2.9999999999999996


In [62]:
b = [[5, 3, 7], [7, 4, 7], [7, 4, 7]]
b = np.matrix(b)
print(np.linalg.det(b))

0.0


In [63]:
b = [[5, 3, 7], [7, 4, 7], [8, 4, 3]]
b = np.matrix(b)
print(np.linalg.det(b))
b[0] *= 5
print(np.linalg.det(b))

-2.9999999999999996
-14.999999999999927
